version :0.2

phases:
  install:
    commands:
      - echo installing depandancies...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm start
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
